version: "3.9"

services:
  frontend:
    platform: linux/amd64  # Ensures compatibility with both macOS and Ubuntu
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - .:/app:cached
      - /app/node_modules   # Avoid overriding node_modules with host version
    command: npm run dev
