#version: '3'
services:
  auth:
    build: ./backend/auth
    volumes:
      - ./backend/auth/db.sqlite:/app/auth-db.sqlite
    ports:
      - "3001:3000"  #TODO: could be changed

  chat:
    build: ./backend/chat
    volumes:
      - ./backend/chat/db.sqlite:/app/chat-db.sqlite
    ports:
      - "3002:3000"

  pong:
    build: ./backend/pong
    volumes:
      - ./backend/pong/db.sqlite:/app/pong-db.sqlite
    ports:
      - "3003:3000"

  users:
    build: ./backend/users
    volumes:
      - ./backend/users/db.sqlite:/app/users-db.sqlite
    ports:
      - "3004:3000"

  # Add ELK and monitoring services later
