services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
      #- "443:443"
    volumes:
      - ./backend/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./backend/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./backend/users/uploads:/app/uploads:ro
      - ./backend/pong/src:/app/pong-static:ro
    depends_on:
      - frontend
      - auth
      - users
      - pong
      - pong-db
    networks:
      - app-network
  auth:
    build: ./backend/auth
    volumes:
      - ./backend/auth/prisma/auth-db.sqlite:/app/prisma/auth-db.sqlite
    #ports:
    #  - "3001:3000"
    environment:
      - JWT_SECRET=change-this-in-prod
      - NODE_ENV=development
    depends_on:
      - users
    networks:
      - app-network  

  pong-db:
    build: ./backend/pong-db
    #ports:
    # - "3003:3000"
    networks:
      - app-network

  pong:
    build: ./backend/pong
    #ports:
    #  - "3002:3000"
    depends_on:
      - auth
      - users
      - pong-db
    networks:
      - app-network

  users:
    build: ./backend/users
    volumes:
      - ./backend/users/prisma/users-db.sqlite:/app/prisma/users-db.sqlite
      - ./backend/users/uploads:/app/uploads
    #ports:
    #  - "3004:3000"
    environment:
      - NODE_ENV=development
      - USERS_URL=http://users:3000 
    networks:
      - app-network
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    #ports:
    #  - "5173:5173"
    volumes:
      - ./frontend:/app:cached
      - .:/workspace:ro
      - /app/node_modules
    command: bash -lc "npm run dev"
    depends_on:
      - auth
    networks:
      - app-network

networks:
  app-network:
    driver: bridge