# TODO: devops
#include:
  #- path: ./devops/includes/compose.elasticsearch.yml
  #- path: ./devops/includes/compose.logstash.yml
  #- path: ./devops/includes/compose.kibana.yml

services:

  # 1 Temporary container to generate TLS certs for ES nodes
  es-setup:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    container_name: es-setup #throwaway-certs
    user: "0"
    command: ["/bin/sh", "/bootstrap/gen-certs.sh"]
    volumes:
      - es_certs:/usr/share/elasticsearch/config/certs
      - ./devops/elk/bootstrap:/bootstrap:ro
    environment:
      ES_PASSWORD: ${ES_PASSWORD}
      KIBANA_SYSTEM_PASSWORD: ${KIBANA_SYSTEM_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/share/elasticsearch/config/certs/es01/es01.crt ]"]
      interval: 2s
      timeout: 5s
      retries: 30
    restart: "no"
    networks:
      - elk-network

# 2 Elasticsearch service config in Dockerfile
  es01:
    build: 
      context: ./devops/elk/elasticsearch
      args: #[STACK_VERSION=${STACK_VERSION}]
        - STACK_VERSION=${STACK_VERSION}
    image: ft/elasticsearch:${STACK_VERSION}
    container_name: es01
    depends_on:
      es-setup:
        condition: service_completed_successfully
    environment:
      - ELASTIC_PASSWORD=${ES_PASSWORD}
      - ES_JAVA_OPTS=${ES_JAVA_HEAP}
      - network.host=0.0.0.0
    volumes:
      - es_data:/usr/share/elasticsearch/data
      - es_certs:/usr/share/elasticsearch/config/certs:ro
    ports:
      - "127.0.0.1:9200:9200"
    networks:
      elk-network:
        aliases: [es01, elasticsearch] # for kibana to reach es01
      app-network:
        aliases: [es01, elasticsearch] # for other services to reach es01
    command: ["/bin/sh","-lc","/usr/local/bin/wait-for-certs && exec /usr/local/bin/docker-entrypoint.sh eswrapper"]
    healthcheck:
      test: ["CMD-SHELL","curl -s --cacert /usr/share/elasticsearch/config/certs/ca/ca.crt https://localhost:9200 | grep -q 'missing authentication credentials'"]
      interval: 10s
      timeout: 5s
      retries: 50

    # 3 Init ES security (set kibana_system, create logstash_writer user)
  es-init:
    image: curlimages/curl:8.10.1
    container_name: es-init
    depends_on:
      es01:
        condition: service_started
      es-setup:
        condition: service_completed_successfully
    entrypoint: ["/bin/sh", "-c"]
    command: ["sh /init/es-init.sh"]
    environment:
      ES_HOST: es01
      ES_PASSWORD: ${ES_PASSWORD}
      KIBANA_SYSTEM_PASSWORD: ${KIBANA_SYSTEM_PASSWORD}
      LOGSTASH_WRITER_USER: ${LOGSTASH_WRITER_USER}
      LOGSTASH_WRITER_PASSWORD: ${LOGSTASH_WRITER_PASSWORD}
    volumes:
      - es_certs:/certs:ro
      - ./devops/elk/bootstrap:/init:ro
    restart: "no"
    networks:
      - elk-network
      #- app-network # TODO: <-- needed here? 

  # 4 Kibana (served over https)
  kibana:
    build:
      context: ./devops/elk/kibana
      args: #[STACK_VERSION=${STACK_VERSION}]
        - STACK_VERSION=${STACK_VERSION}
    image: ft/kibana:${STACK_VERSION}
    container_name: kibana
    depends_on:
      es-setup:
        condition: service_completed_successfully
      es01:
        condition: service_started
        #condition: service_completed_successfully
    environment:
      SERVER_SSL_ENABLED: "true"
      SERVER_SSL_CERTIFICATE: "/usr/share/kibana/config/certs/kibana/kibana.crt"
      SERVER_SSL_KEY: "/usr/share/kibana/config/certs/kibana/kibana.key"
      ELASTICSEARCH_HOSTS: "https://es01:9200"
      ELASTICSEARCH_USERNAME: "kibana_system" # set in .env file
      ELASTICSEARCH_PASSWORD: ${KIBANA_SYSTEM_PASSWORD} # set in .env file
      ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES: "/usr/share/kibana/config/certs/ca/ca.crt"
      XPACK_SECURITY_ENCRYPTIONKEY: ${ENCRYPTION_KEY} # set in .env file
      XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY: ${ENCRYPTION_KEY} # set in .env file
      XPACK_REPORTING_ENCRYPTIONKEY: ${ENCRYPTION_KEY} # set in .env file
    volumes:
      - es_certs:/usr/share/kibana/config/certs:ro
    ports:
      - "127.0.0.1:5601:5601"
    networks:
      elk-network: {}
      #   aliases: [es01, elasticsearch] # for kibana to reach es01
      # app-network:
      #   aliases: [es01, elasticsearch] # for other services to reach es01

  # 5 Logstash (TLS Beats input)
  logstash:
    build:
      context: ./devops/elk/logstash
      args: #[STACK_VERSION=${STACK_VERSION}]
        - STACK_VERSION=${STACK_VERSION}
    image: ft/logstash:${STACK_VERSION}
    container_name: logstash
    depends_on:
      es-setup:
        condition: service_completed_successfully
      es01:
        condition: service_started
    environment:
      LS_JAVA_OPTS: ${LOGSTASH_JAVA_HEAP}
      ELASTICSEARCH_USERNAME: ${LOGSTASH_WRITER_USER} # set in .env file
      ELASTICSEARCH_PASSWORD: ${LOGSTASH_WRITER_PASSWORD} # set in .env file
      ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES: "/usr/share/logstash/certs/ca/ca.crt"
      ELASTICSEARCH_HOSTS: "https://es01:9200"
    volumes:
      - es_certs:/usr/share/logstash/certs:ro
    ports:
      - "127.0.0.1:5044:5044"
    restart: unless-stopped
    networks:
      elk-network: {}
      #   aliases: [es01, elasticsearch] # for logstash to reach es01
      # app-network:
      #   aliases: [es01, elasticsearch] # for other services to reach es01
  
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      #- "443:443"
    volumes:
      - ./backend/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./backend/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./backend/users/uploads:/app/uploads:ro
      - ./backend/pong/src:/app/pong-static:ro
    depends_on:
      - frontend
      - auth
      - users
      - pong
      - pong-db
      - es01
    networks:
      - app-network
  auth:
    build: ./backend/auth
    volumes:
      - ./backend/auth/prisma/auth-db.sqlite:/app/prisma/auth-db.sqlite
    #ports:
    #  - "3001:3000"
    environment:
      - JWT_SECRET=change-this-in-prod
      - NODE_ENV=development
    depends_on:
      - users
    networks:
      - app-network  

  pong-db:
    build: ./backend/pong-db
    #ports:
    # - "3003:3000"
    networks:
      - app-network

  pong:
    build: ./backend/pong
    #ports:
    #  - "3002:3000"
    depends_on:
      - auth
      - users
      - pong-db
    networks:
      - app-network

  users:
    build: ./backend/users
    volumes:
      - ./backend/users/prisma/users-db.sqlite:/app/prisma/users-db.sqlite
      - ./backend/users/uploads:/app/uploads
    #ports:
    #  - "3004:3000"
    environment:
      - NODE_ENV=development
      - USERS_URL=http://users:3000 
    networks:
      - app-network
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    #ports:
    #  - "5173:5173"
    volumes:
      - ./frontend:/app:cached
      - .:/workspace:ro
      - /app/node_modules
    command: bash -lc "npm run dev"
    depends_on:
      - auth
    networks:
      - app-network
    

# TODO: devops
networks:
  elk-network:
    driver: bridge
  app-network:
    driver: bridge

# TODO: devops
volumes:
  #esdata: {}
  es_data: 
    name: ft_es_data # how does this work? 
  es_certs: 
    name: ft_es_certs # TLS certs for ES nodes 





  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:8.15.1 # 9.x not released yet; pinned for reproducibility
  #   container_name: elasticsearch
  #   environment:
  #     - "discovery.type=single-node" # needed for ES 8.x
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m" # adjust heap size as needed
  #     - "ELASTIC_PASSWORD=${ES_PASSWORD}" # set in .env file
  #   restart: always
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #   volumes:
  #     - elastic_data:/usr/share/elasticsearch/data
  #     # Mount our custom elasticsearch.yml (path is relative to this include file)
  #     - ./devops/elk/elasticsearch/conf/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
  #   ports:
  #     - '9200:9200'
  #   healthcheck:
  #     test: ["CMD-SHELL","curl -fs http://localhost:9200 >/dev/null || exit 1"]
  #     interval: 15s
  #     timeout: 5s
  #     retries: 20
  #   networks:
  #     - elk-network
  #     - app-network
  # logstash:
  #   image: logstash:8.15.1
  #   container_name: logstash
  #   restart: always
  #   volumes:
  #     - ./logstash/:/logstash_dir
  #   command: logstash -f /logstash_dir/pipeline/logstash.conf
  #   depends_on:
  #     - elasticsearch
  #   ports:
  #     - '5044:5044'
  #   environment:
  #     - LS_JAVA_OPTS= Xmx256m -Xms256m
  #     - ELASTICSEARCH_USERNAME=${ES_USER} # set in .env file
  #     - ELASTICSEARCH_PASSWORD=${ES_PASSWORD} # set in .env file
  #   networks:
  #     - elk-network

  # kibana:
  #   image: kibana:8.15.1
  #   container_name: kibana
  #   restart: always
  #   ports:
  #     - '5601:5601'
  #   environment:
  #     - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
  #     - ELASTICSEARCH_USERNAME=${ES_USER} # set in .env file
  #     - ELASTICSEARCH_PASSWORD=${ES_PASSWORD} # set in .env file
  #   depends_on:
  #     - elasticsearch
  #   networks:
  #     - elk-network