services:
  es-setup:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    container_name: es-setup #throwaway-certs
    user: "0"
    command: ["/bin/sh", "/bootstrap/gen-certs.sh"]
    volumes:
      - es_certs:/usr/share/elasticsearch/config/certs
      - ./devops/elk/bootstrap:/bootstrap:ro
    environment:
      ES_PASSWORD: ${ES_PASSWORD}
      KIBANA_SYSTEM_PASSWORD: ${KIBANA_SYSTEM_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/share/elasticsearch/config/certs/es01/es01.crt ]"]
      interval: 2s
      timeout: 5s
      retries: 30
    restart: "no"
    networks:
      - app-network
  es01:
    build: 
      context: ./devops/elk/elasticsearch
      args: #[STACK_VERSION=${STACK_VERSION}]
        - STACK_VERSION=${STACK_VERSION}
    image: ft/elasticsearch:${STACK_VERSION}
    container_name: es01
    depends_on:
      es-setup:
        condition: service_completed_successfully
    environment:
      - ELASTIC_PASSWORD=${ES_PASSWORD}
      - ES_JAVA_OPTS=${ES_JAVA_HEAP}
      - network.host=0.0.0.0
    volumes:
      - es_data:/usr/share/elasticsearch/data
      - es_certs:/usr/share/elasticsearch/config/certs:ro
    ports:
      - "9200:9200"
    networks:
      app-network:
        aliases: [es01, elasticsearch] # for other services to reach es01
    command: ["/bin/sh","-lc","/usr/local/bin/wait-for-certs && exec /usr/local/bin/docker-entrypoint.sh eswrapper"]
    healthcheck:
      test: ["CMD-SHELL","curl -s --cacert /usr/share/elasticsearch/config/certs/ca/ca.crt https://localhost:9200 | grep -q 'missing authentication credentials'"]
      interval: 10s
      timeout: 5s
      retries: 50
  es-init:
    image: curlimages/curl:8.10.1
    container_name: es-init
    depends_on:
      es01:
        condition: service_started
      es-setup:
        condition: service_completed_successfully
    entrypoint: ["/bin/sh", "-c"]
    command: ["sh /init/es-init.sh"]
    environment:
      ES_HOST: es01
      ES_PASSWORD: ${ES_PASSWORD}
      KIBANA_SYSTEM_PASSWORD: ${KIBANA_SYSTEM_PASSWORD}
      LOGSTASH_WRITER_USER: ${LOGSTASH_WRITER_USER}
      LOGSTASH_WRITER_PASSWORD: ${LOGSTASH_WRITER_PASSWORD}
    volumes:
      - es_certs:/certs:ro
      - ./devops/elk/bootstrap:/init:ro
    restart: "no"
    networks:
      - app-network
  kibana:
    build:
      context: ./devops/elk/kibana
      args: #[STACK_VERSION=${STACK_VERSION}]
        - STACK_VERSION=${STACK_VERSION}
    image: ft/kibana:${STACK_VERSION}
    container_name: kibana
    depends_on:
      es-setup:
        condition: service_completed_successfully
      es01:
        condition: service_started
        #condition: service_completed_successfully
    environment:
      SERVER_SSL_ENABLED: "true"
      SERVER_SSL_CERTIFICATE: "/usr/share/kibana/config/certs/kibana/kibana.crt"
      SERVER_SSL_KEY: "/usr/share/kibana/config/certs/kibana/kibana.key"
      ELASTICSEARCH_HOSTS: "https://es01:9200"
      ELASTICSEARCH_USERNAME: "kibana_system" # set in .env file
      ELASTICSEARCH_PASSWORD: ${KIBANA_SYSTEM_PASSWORD} # set in .env file
      ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES: "/usr/share/kibana/config/certs/ca/ca.crt"
      XPACK_SECURITY_ENCRYPTIONKEY: ${ENCRYPTION_KEY} # set in .env file
      XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY: ${ENCRYPTION_KEY} # set in .env file
      XPACK_REPORTING_ENCRYPTIONKEY: ${ENCRYPTION_KEY} # set in .env file
    volumes:
      - es_certs:/usr/share/kibana/config/certs:ro
    ports:
      - "5601:5601"
    networks:
      app-network: {}
  logstash:
    build:
      context: ./devops/elk/logstash
      args: #[STACK_VERSION=${STACK_VERSION}]
        - STACK_VERSION=${STACK_VERSION}
    image: ft/logstash:${STACK_VERSION}
    container_name: logstash
    depends_on:
      es-setup:
        condition: service_completed_successfully
      es01:
        condition: service_started
    environment:
      LS_JAVA_OPTS: ${LOGSTASH_JAVA_HEAP}
      ELASTICSEARCH_USERNAME: ${LOGSTASH_WRITER_USER} # set in .env file
      ELASTICSEARCH_PASSWORD: ${LOGSTASH_WRITER_PASSWORD} # set in .env file
      ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES: "/usr/share/logstash/certs/ca/ca.crt"
      ELASTICSEARCH_HOSTS: "https://es01:9200"
    volumes:
      - es_certs:/usr/share/logstash/certs:ro
    ports:
      - "5044:5044"
    restart: unless-stopped
    networks:
      app-network: {}

networks:
  app-network:
    driver: bridge

volumes:
  #esdata: {}
  es_data: 
    name: ft_es_data # how does this work? 
  es_certs: 
    name: ft_es_certs # TLS certs for ES nodes 