input {
  gelf {
    port => 12201
    type => "gelf"
  }
}


filter {
  json { source => "short_message" target => "event" remove_field => ["short_message"] }

  mutate {
    rename => {
      "facility"       => "[docker][facility]"
      "host"           => "[docker][host]"
      "container_name" => "[docker][container_name]"
      "level"          => "[log][level]"
    }
  }

  mutate {
    add_field => { "[service][name]" => "%{[docker][container_name]}" }
  }

  if ![event] {
    mutate { rename => { "full_message" => "message" } }
  }
}


output {
  elasticsearch {
    hosts  => ["${ELASTICSEARCH_HOSTS}"]
    user   => "${ELASTICSEARCH_USERNAME}"
    password => "${ELASTICSEARCH_PASSWORD}"

    ssl_enabled => true
    ssl_certificate_authorities => ["/usr/share/logstash/certs/ca/ca.crt"]

    index => "logs-%{+YYYY.MM.dd}"

    manage_template => false
    ilm_enabled     => false
  }
  stdout { codec => rubydebug }
}