input {
  gelf {
    port => 12201
    type => "gelf"
  }
}

filter {
  if [tag] == "nginx" and [message] =~ /HTTP\/1\.[01]/ {
    grok {
      match => {
        "message" => [
          '%{IPORHOST:client.ip} - %{DATA:user.name} \[%{HTTPDATE:nginx.time}\] "%{WORD:http.request.method} %{DATA:url.original} HTTP/%{NUMBER:http.version}" %{NUMBER:http.response.status_code:int} (?:%{NUMBER:http.response.body.bytes:int}|-) "%{DATA:http.request.referrer}" "%{DATA:user_agent.original}" "%{DATA:nginx.upstream}"'
        ]
      }
      tag_on_failure => ["_grok_nginx_fail"]
    }

    dissect {
      mapping => {
        "url.original" => "%{url.path}?%{url.query}"
      }
    }

    date {
      match => ["nginx.time", "dd/MMM/YYYY:HH:mm:ss Z"]
      target => "@timestamp"
      timezone => "UTC"
    }

    useragent {
      source => "user_agent.original"
      target => "user_agent"
    }

    geoip {
      source => "client.ip"
      target => "[client][geo]"
      ecs_compatibility => v8
    }

    mutate {
      add_field => {
        "[service][type]" => "nginx"
      }
      rename => { "nginx.upstream" => "[nginx][upstream]" }
      remove_field => ["nginx.time"]
    }
  }

  translate {
    source => "[log][level]"
    target => "[log][level]"
    override => true
    dictionary => {
      "0" => "emergency"
      "1" => "alert"
      "2" => "critical"
      "3" => "error"
      "4" => "warning"
      "5" => "notice"
      "6" => "info"
      "7" => "debug"
    }
  }

  mutate {
    convert => {
      "http.response.status_code" => "integer"
      "http.response.body.bytes"  => "integer"
    }
  }
}

output {
  elasticsearch {
    hosts  => ["${ELASTICSEARCH_HOSTS}"]
    user   => "${ELASTICSEARCH_USERNAME}"
    password => "${ELASTICSEARCH_PASSWORD}"

    ssl_enabled => true
    ssl_certificate_authorities => ["/usr/share/logstash/certs/ca/ca.crt"]


    ilm_enabled     => true
    ilm_rollover_alias => "logs"
    ilm_pattern => "000001"
    ilm_policy => "logs_policy"
   
    manage_template => false
  }
  stdout { codec => rubydebug }
}