input {
  beats {
    port => 5044
    ssl_enabled => true
    ssl_certificate => "/usr/share/logstash/certs/logstash/logstash.crt"
    ssl_key         => "/usr/share/logstash/certs/logstash/logstash.key"

    # choose ONE of the following:
    ssl_client_authentication => none         # server-auth only
    # ssl_client_authentication => required   # mTLS: then also set:
    # ssl_certificate_authorities => ["/usr/share/logstash/certs/ca/ca.crt"]
  }
}

filter { }

output {
  elasticsearch {
    hosts  => ["${ELASTICSEARCH_HOSTS}"]
    user   => "${ELASTICSEARCH_USERNAME}"
    password => "${ELASTICSEARCH_PASSWORD}"

    ssl_enabled => true
    ssl_certificate_authorities => ["/usr/share/logstash/certs/ca/ca.crt"]

    index => "logs-%{+YYYY.MM.dd}"

    # turn off features that need extra cluster perms
    manage_template => false
    ilm_enabled     => false
  }
}



# input {
#   beats {
#     port => 5044
#     ssl  => true
#     ssl_certificate => "/usr/share/logstash/certs/logstash/logstash.crt"
#     ssl_key         => "/usr/share/logstash/certs/logstash/logstash.key"
#     ssl_certificate_authorities => ["/usr/share/logstash/certs/ca/ca.crt"]
#     ssl_verify_mode  => "force_peer"      # require & verify client cert
#     # ssl_verify_mode => "force_peer"
#     # cacert => "/usr/share/logstash/config/certs/ca/ca.crt"
#   }
# }

# filter { }

# output {
#   elasticsearch {
#     hosts    => ["${ELASTICSEARCH_HOSTS}"]
#     user     => "${ELASTICSEARCH_USERNAME}"
#     password => "${ELASTICSEARCH_PASSWORD}"
#     ssl      => true
#     cacert   => "/usr/share/logstash/certs/ca/ca.crt"
#     index    => "logs-%{+YYYY.MM.dd}"

#     # Turn off features that need extra perms:
#     ilm_enabled     => false
#     manage_template => false
#     # (optional) if you still hit 403 on root health:
#     # healthcheck => false
#   }
# }

